<h2 style="color:navy"><u>Practical : 5</u></h2>

**<h4><u>Write a Pandas program to implement following operation</u></h4>**

* to convert a NumPy array to a Pandas series

In [ ]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3, 4, 5])

series = pd.Series(arr)

print("Series is:\n",series)

* to convert the first column of a DataFrame as a Series

In [ ]:
import pandas as pd


dic1 = {
    "name": ["a", "b", "c", "d"],
    "marks": [10, 20, 30, 40],
    "city": ["PBR", "MUM", "PBR", "MUM"]
}

df = pd.DataFrame(dic1)
col = df.iloc[:, 0]

print("Convert the first column of dataframe",col)

* to create the mean and standard deviation of the data of a given Series

In [ ]:
import pandas as pd

series = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = series.mean()
deviation = series.std()

print("Mean:", mean)
print("Standard Deviation:", deviation)

* to sort a given Series

In [ ]:
import pandas as pd

series = pd.Series([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

sort = series.sort_values()

print("Sorted Series in ascending order:\n", sort)